#ifndef __CVM_OPCODES__
#define __CVM_OPCODES__
/* DO NOT EDIT: AUTOMATICALLY GENERATED BY cvmc/binary.py */

#include <stdlib.h>
#define NOP 0
#define HALT 1
#define STORE 2
#define LOAD 3
#define INCR 4
#define DECR 5
#define NOT 6
#define BNOT 7
#define MUL 8
#define ADD 9
#define SUB 10
#define DIV 11
#define MOD 12
#define AND 13
#define OR 14
#define LSH 15
#define RSH 16
#define BAND 17
#define BOR 18
#define EQ 19
#define GEQ 20
#define LEQ 21
#define GT 22
#define LT 23
#define NEQ 24
#define XOR 25
#define ADDR 26
#define OZJMP 27
#define ONZJMP 28
#define OJMP 29
#define LDCONST 30
#define PRINT 31
char **opcode_map() {
  char **opcode_names = malloc(32 * sizeof(char *));
  opcode_names[NOP] = "NOP";
  opcode_names[HALT] = "HALT";
  opcode_names[STORE] = "STORE";
  opcode_names[LOAD] = "LOAD";
  opcode_names[INCR] = "INCR";
  opcode_names[DECR] = "DECR";
  opcode_names[NOT] = "NOT";
  opcode_names[BNOT] = "BNOT";
  opcode_names[MUL] = "MUL";
  opcode_names[ADD] = "ADD";
  opcode_names[SUB] = "SUB";
  opcode_names[DIV] = "DIV";
  opcode_names[MOD] = "MOD";
  opcode_names[AND] = "AND";
  opcode_names[OR] = "OR";
  opcode_names[LSH] = "LSH";
  opcode_names[RSH] = "RSH";
  opcode_names[BAND] = "BAND";
  opcode_names[BOR] = "BOR";
  opcode_names[EQ] = "EQ";
  opcode_names[GEQ] = "GEQ";
  opcode_names[LEQ] = "LEQ";
  opcode_names[GT] = "GT";
  opcode_names[LT] = "LT";
  opcode_names[NEQ] = "NEQ";
  opcode_names[XOR] = "XOR";
  opcode_names[ADDR] = "ADDR";
  opcode_names[OZJMP] = "OZJMP";
  opcode_names[ONZJMP] = "ONZJMP";
  opcode_names[OJMP] = "OJMP";
  opcode_names[LDCONST] = "LDCONST";
  opcode_names[PRINT] = "PRINT";
  return opcode_names;
}
#endif
